env:
  browser: true
  commonjs: true
  es2020: true
extends:
  - airbnb-base
  - plugin:react/recommended
parserOptions:
  ecmaVersion: 11
rules:
  react/prop-types: 0
  newline-per-chained-call: 0
  no-tabs: 0
  indent: 0
  object-curly-newline: 0
  no-underscore-dangle: 0
  prefer-rest-params: 0
  no-unused-vars:
    - error
    - varsIgnorePattern: Fragment
  no-whitespace-before-property: 2
  no-console: error
  arrow-parens: 0
  no-shadow: 0
  implicit-arrow-linebreak: 0
  operator-linebreak: 0
  function-paren-newline: 0
  curly: 0
  nonblock-statement-body-position: 0
  no-confusing-arrow: 0
  object-curly-spacing:
    - error
    - always
  comma-dangle:
    - error
    - never
  semi:
    - error
    - never
  block-spacing:
    - 2
    - always
  arrow-spacing:
    - error
    - before: true
      after: true
  quotes:
    - error
    - single
    - avoidEscape: true
  quote-props:
    - error
    - as-needed
    - keywords: false
  space-unary-ops:
    - 2
    - words: true
      nonwords: false
      overrides:
        new: true
        '=': true
  prefer-destructuring:
    - error
    - array: true
      object: true
    - enforceForRenamedProperties: false
  prefer-const:
    - error
    - destructuring: any
      ignoreReadBeforeAssign: false
